[book]
authors = ["huhn511"]
language = "en"
multilingual = false
src = "./docs"
title = "IOTA Identity"

[output.html]
default-theme = "iota"
theme = "docs/.config/theme"

[build]
build-dir = "book"
create-missing = false
