[workspace]
members = [
  "identity-core",
  "identity-credential",
  "identity-diff",
  "identity-iota",

  "examples/credential",
  "examples/diff-chain",
  "examples/resolution",
]

exclude = [
  "bindings/wasm",
]
