[workspace]
members = [
    "identity_actor",
    "identity_core",
    "identity_derive",
    "identity_diff",
    "identity_iota",
    "identity_proof",
    "identity_comm",
]
exclude = [
    "libraries/wasm"
]
