[package]
name = "identity_integration"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A DID to ledger intergration library for IOTA"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0/MIT"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
