[package]
name = "identity_core"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "An implementation of the Decentralized Identifiers (DID) standard"
readme = "../README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity"]
homepage = "https://www.iota.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error handling
thiserror = "1.0"
anyhow = "1.0"

# serialization
serde = {version = "1.0", features = ["derive"]}

# parser crates
pest = "2.1"
pest_derive = "2.1"

[dev-dependencies]
# assertion macros
totems = "0.2.7"

# generative/property testing
proptest = "0.10"