[package]
name = "internal"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "Derive macros for diff"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
