[package]
name = "examples"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
identity-core = { path = "../identity-core" }
identity-credential = { path = "../identity-credential" }
identity-did = { path = "../identity-did" }
identity-iota = { path = "../identity-iota" }
smol = { version = "0.1.18", features = ["tokio02"] }
smol-potat = { version = "0.3" }

[[example]]
name = "credential"
path = "credential.rs"

[[example]]
name = "diff_chain"
path = "diff_chain.rs"

[[example]]
name = "resolution"
path = "resolution.rs"
