[package]
name = "libjose"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A library for JOSE (JSON Object Signing and Encryption)"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "jose", "jwa", "jwe", "jwk", "jws", "jwt"]
homepage = "https://www.iota.org"

[dependencies]
base64 = { version = "0.12", default-features = false }
miniz_oxide = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
url = { version = "2.1", default-features = false, features = ["serde"] }

curve25519-dalek = { version = "3.0", default-features = false }
k256 = { version = "0.7", default-features = false, features = ["ecdsa", "sha256", "zeroize"] }
p256 = { version = "0.7", default-features = false, features = ["ecdsa", "sha256", "zeroize"] }
rand = { version = "0.7", default-features = false, features = ["getrandom"] }
rsa = { version = "0.3", default-features = false }
sha2 = { version = "0.9", default-features = false }
x25519-dalek = { version = "1.1", default-features = false }

[features]
default = ["std", "pem"]

std = [
  "alloc",
  "serde/std",
  "serde_json/std",
]

alloc = [
  "base64/alloc",
  "serde/alloc",
  "serde_json/alloc",
]

pem = ["rsa/pem"]
