[package]
name = "libjose"
version = "0.1.0"
authors = ["IOTA Identity"]
edition = "2018"
description = "A library for JOSE (JSON Object Signing and Encryption)"
readme = "README.md"
repository = "https://github.com/iotaledger/identity.rs"
license = "Apache-2.0"
keywords = ["iota", "tangle", "identity", "jose", "jwa", "jwe", "jwk", "jwm", "jws", "jwt"]
homepage = "https://www.iota.org"

[dependencies]
base64 = { version = "0.12", default-features = false }
miniz_oxide = { version = "0.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
url = { version = "2.1", default-features = false, features = ["serde"] }

rand = { version = "0.7", default-features = false, features = ["getrandom"] }
rsa = { version = "0.3", default-features = false }
sha-1 = { version = "0.9", default-features = false }
sha2 = { version = "0.9", default-features = false }
subtle = { version = "2.4", default-features = false }

[dependencies.crypto]
git = "https://github.com/iotaledger/crypto.rs"
branch = "libjose"
# path = "../../crypto.rs"
package = "iota-crypto"
default-features = false
features = [
  "aes",
  "aes-cbc",
  "aes-kw",
  "chacha",
  "nist-p256",
  "ed25519",
  "hmac",
  "pbkdf",
  "random",
  "secp256k1",
  "sha",
  "x25519",
  "x448",
]

[features]
default = ["std"]

std = [
  "alloc",
  "serde/std",
  "serde_json/std",
]

alloc = [
  "base64/alloc",
  "serde/alloc",
  "serde_json/alloc",
]
